name: Build & Deploy Blender Extension Repo

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build Repository
        env:
          BASE_URL: https://scorpion81.github.io/blender-extension-repo
        run: |
          pip install --upgrade pip
          pip install packaging
          mkdir -p repo
          python scripts/generate_repo.py

      - name: Upload repo artifact
        uses: actions/upload-artifact@v4
        with:
          name: repo
          path: repo

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Download repo artifact
        uses: actions/download-artifact@v4
        with:
          name: repo
          path: repo

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./repo
          publish_branch: gh-pages
